department-of-veterans-affairs/health-apis-patient-generated-data

patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/QuestionnaireController.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/QuestionnaireControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/WebExceptionHandlerTest.java
https://vajira.max.gov/browse/API-3362
=> API-3362 questionnaire update

patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/OpenApiIT.java, patient-generated-data/pom.xml, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/HomeController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/OpenApi.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/OpenApiController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/patient/PatientApi.java
https://vajira.max.gov/browse/API-2843
`curl -s http://localhost:8095/r4/`
`curl -s http://localhost:8095/r4/openapi.json`
=> API-2843 initial swagger

patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ObservationIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/OpenApiIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/PatientIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseIT.java
https://vajira.max.gov/browse/API-3918
I executed all of the ITs from my GFE against the lab environment to verify they pass.
=> API-3918 enable integration tests in lab

patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/OpenApiIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/PatientIT.java
- Enable `OpenApiIT` in lab
- Make `PatientIT.read_notMe()` provisional for lab
=> API-2962 tweak ITs for lab

patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationApi.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/patient/PatientApi.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/patient/PatientController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/observation/ObservationControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/patient/PatientControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseControllerTest.java
https://vajira.max.gov/browse/API-4069
Follow-up to https://github.com/department-of-veterans-affairs/health-apis-patient-generated-data/pull/39
=> API-4069 populate X-VA-INCLUDES-ICN header on update

patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ObservationIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/OpenApiIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/PatientIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseUpdateIT.java
https://vajira.max.gov/browse/API-4144
=> API-4144 enable QR author and authored date ITs

patient-generated-data-tests/src/main/docker/Dockerfile, patient-generated-data-tests/src/main/docker/entrypoint.sh
https://vajira.max.gov/browse/API-4169
=> API-4169 docker timeout workaround

patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ObservationCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ObservationIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/PatientCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseIT.java
Standardize ITs across environments after last MR: https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/133
1. `Update` tests only run in lower environments
2. `Create` tests only run locally
3. All other tests run everywhere
=> IT environment updates

patient-generated-data-synthetic/pom.xml, patient-generated-data/pom.xml
https://vajira.max.gov/browse/API-4334
=> API-4334 Make app available as library for synthetic-data module

patient-generated-data-synthetic/src/test/java/gov/va/api/health/patientgenerateddata/Populaterator.java
=> Replaced Populaterator specific code for code used in main project

patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/patient/PatientController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java
https://vajira.max.gov/browse/API-4588
Reduce noise for https://github.com/department-of-veterans-affairs/health-apis-patient-generated-data/pull/62
=> API-4588 Mark populate/toEntity methods as static

patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseUpdateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireUpdateIT.java
https://vajira.max.gov/browse/API-4641
=> API-4641 enable ITs in lab

patient-generated-data-synthetic/src/test/java/gov/va/api/health/patientgenerateddata/Populaterator.java, patient-generated-data-tests/pom.xml, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/RequestUtils.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/SyntheticRefresh.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/JacksonMapperConfig.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/PayloadEntity.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/WebExceptionHandler.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/patient/PatientController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/JacksonMapperConfigTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/observation/ObservationControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/patient/PatientControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseControllerTest.java
https://vajira.max.gov/browse/API-5196
Centralize ObjectMapper references in preparation for upgrading health-apis-fhir-resources.
=> API-5196 mapper refactor

patient-generated-data-synthetic/src/test/resources/questionnaire-response/f003043a-9047-4c3a-b15b-a26c67f4e723.json, patient-generated-data-synthetic/src/test/resources/questionnaire/37953b72-961b-41ee-bd05-86c62bacc46b.json, patient-generated-data-tests/src/main/java/gov/va/api/health/patientgenerateddata/tests/SystemDefinitions.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseIT.java
https://vajira.max.gov/browse/API-5271
=> API-5271 update synthetic data for latest clipboard mappings

patient-generated-data-synthetic/src/test/resources/questionnaire/37953b72-961b-41ee-bd05-86c62bacc46b.json, patient-generated-data-tests/src/main/java/gov/va/api/health/patientgenerateddata/tests/SystemDefinitions.java
https://vajira.max.gov/browse/API-5749
=> API-5749 update synthetic questionnaire usecontext to match dq sandbox

patient-generated-data/pom.xml, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java
Update Vulcan and replace deprecated `csvList` mappings
=> API-6324 update vulcan

patient-generated-data/README.md
Update documentation + allow promotatron to upgrade DU encryption
=> documentation

patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/OpenApi.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationApi.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireApi.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseApi.java
Document scopes in Swagger
Bonus, fix structural errors in Observation
=> API-8019 document scopes

patient-generated-data-synthetic/src/test/resources/questionnaire-response/f003043a-9047-4c3a-b15b-a26c67f4e723.json, patient-generated-data-synthetic/src/test/resources/questionnaire/37953b72-961b-41ee-bd05-86c62bacc46b.json, patient-generated-data-tests/src/main/java/gov/va/api/health/patientgenerateddata/tests/SystemDefinitions.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseIT.java
Remove the application tag from synthetic data:
``` 
"meta" : {
"tag" : [
{
"system" : "https://api.va.gov/services/pgd",
"code" : "66a5960c-68ee-4689-88ae-4c7cccf7ca79",
"display" : "TEST APP"
}
]
}
```
=> API-9620 remove application tag from synthetic data

patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/ManagementController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/WebExceptionHandler.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/CompositeMappingJpaTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/ManagementControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/SourcererTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/observation/ObservationControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaire/Samples.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/Samples.java
Follow-up to https://github.com/department-of-veterans-affairs/health-apis-patient-generated-data/pull/113
=> API-9550 Populate source for Questionnaire and QuestionnaireResponse

patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ManagementControllerGetIdsIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/RequestUtils.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/ManagementController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/ManagementControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/observation/ObservationControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseControllerTest.java
Updated to get all IDs from select resources (Observation, Questionnaire, and QuestionnaireResponse).
=> Get IDs for resources

patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ManagementControllerCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseUpdateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireUpdateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/SandboxDeleteIT.java
- Allow `SandboxDeleteIT` to run in `staging`
- Make create/update ITs clean up after themselves
=> API-9761 SandboxDeleteIT in staging + self-cleaning tests

patient-generated-data-tests/src/main/java/gov/va/api/health/patientgenerateddata/tests/SystemDefinitions.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ManagementControllerCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ObservationCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/ObservationIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseCreateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseUpdateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireUpdateIT.java
=> API-9771 enable ITs in more environments

patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/ManagementController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/ManagementControllerTest.java
Added ability to update all resource paths.
=> API-9767 update production source paths

patient-generated-data-synthetic/src/test/java/gov/va/api/health/patientgenerateddata/Populaterator.java, patient-generated-data-tests/pom.xml, patient-generated-data-tests/src/main/java/gov/va/api/health/patientgenerateddata/tests/SystemDefinitions.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireResponseUpdateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/QuestionnaireUpdateIT.java, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/RequestUtils.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/Controllers.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/Exceptions.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/WebExceptionHandler.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/observation/ObservationController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireController.java, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/ControllersTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/WebExceptionHandlerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/observation/ObservationControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseControllerTest.java
Check source matching data before running updates on resources.
=> API-9680 check for matching sources before update

patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseController.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseControllerTest.java
Add patient-matching and population of the `X-VA-INCLUDES-ICN` header
=> API-10307 patient matching

patient-generated-data-synthetic/pom.xml, patient-generated-data-tests/pom.xml, patient-generated-data-tests/src/test/java/gov/va/api/health/patientgenerateddata/tests/Requests.java, patient-generated-data/pom.xml, patient-generated-data/src/main/java/gov/va/api/health/patientgenerateddata/JacksonMapperConfig.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/IncludesIcnMajigTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/JacksonMapperConfigTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/VulcanizedBundlerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/observation/ObservationControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaire/QuestionnaireControllerTest.java, patient-generated-data/src/test/java/gov/va/api/health/patientgenerateddata/questionnaireresponse/QuestionnaireResponseControllerTest.java, pom.xml
Upgrade to `health-apis-parent` `9.0.6` and `fhir-resources` `10.0.3`
=> upgrade dependencies

patient-generated-data-tests/src/main/java/gov/va/api/health/patientgenerateddata/tests/SystemDefinitions.java
Updated system definitions to use patient-generated-data instead of pgd/v0
=> API-12682 SystemDefinitions pgd/v0 -> patient-generated-data
